/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/gloves.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    rings_1: THREE.Mesh
    string_1: THREE.Mesh
    gloves_1: THREE.Mesh
  }
  materials: {
    rings_1001: THREE.MeshStandardMaterial
    strings_1001: THREE.MeshStandardMaterial
    gloves_1001: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gloves.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.rings_1.geometry} material={materials.rings_1001} />
        <mesh geometry={nodes.string_1.geometry} material={materials.strings_1001} />
        <mesh geometry={nodes.gloves_1.geometry} material={materials.gloves_1001} />
      </group>
    </group>
  )
}

useGLTF.preload('/gloves.glb')
