import { useEffect, useRef, useState } from 'react'
import { motion, useScroll, useTransform } from 'framer-motion'

// ---------------------------------------------------------------------------
// Centerline path — S-curves descending from top-center, ending in a dramatic
// two-loop spiral. ViewBox: 0 0 1000 4200. The path origin (~520, 0) aligns
// with the graffiti Y's tail position (horizontally centered in the hero image).
// ---------------------------------------------------------------------------

const CENTERLINE_D = [
  'M 520 0',
  'C 520 180, 780 320, 740 520',
  'C 700 720, 200 700, 260 960',
  'C 340 1200, 820 1300, 760 1560',
  'C 700 1820, 160 1780, 240 2040',
  'C 360 2300, 800 2380, 720 2640',
  'C 640 2900, 180 2860, 280 3100',
  'C 420 3340, 740 3400, 660 3520',
  // Spiral — loop 1 (wide)
  'C 720 3600, 700 3760, 600 3840',
  'C 480 3940, 300 3880, 300 3740',
  'C 300 3600, 440 3540, 540 3600',
  // Spiral — loop 2 (tight)
  'C 620 3650, 610 3760, 540 3800',
  'C 470 3840, 390 3810, 390 3750',
  'C 390 3690, 440 3660, 480 3690',
  // Tail flick
  'C 510 3715, 520 3710, 510 3700',
].join(' ')

// ---------------------------------------------------------------------------
// Filled brush outline — variable-width shape traced from the centerline.
// Thick (44 SVG units) at the top, tapering to a fine point (~2.5 units)
// at the spiral tip. Generated by offsetting perpendicular to the tangent
// at sampled points along the centerline with a multi-phase width profile.
// ---------------------------------------------------------------------------

const BRUSH_OUTLINE_D = `M 498.1 2.3 L 502.6 44.1 L 515.1 86.3 L 533.6 126.7 L 556.5 165.6 L 582.1 203.5 L 609.1 240.7 L 636.0 277.6 L 661.4 314.3 L 683.9 351.1 L 702.3 388.1 L 715.2 425.4 L 721.7 463.3 L 720.8 501.8 L 710.8 539.3 L 689.0 571.3 L 655.9 600.1 L 613.2 626.5 L 563.5 650.9 L 509.5 674.2 L 453.8 697.6 L 399.0 722.5 L 347.6 750.1 L 302.1 782.4 L 265.4 821.2 L 241.3 868.1 L 233.6 923.9 L 246.7 985.3 L 277.4 1040.1 L 318.1 1089.3 L 366.4 1134.5 L 419.6 1176.8 L 475.5 1217.2 L 531.7 1256.6 L 585.8 1295.6 L 635.4 1335.0 L 678.1 1375.3 L 711.6 1416.7 L 734.1 1459.8 L 744.1 1505.4 L 739.8 1555.3 L 720.9 1603.6 L 689.4 1644.6 L 647.1 1680.2 L 596.2 1711.3 L 539.5 1739.1 L 479.7 1764.7 L 419.7 1789.7 L 362.2 1815.6 L 309.8 1844.1 L 265.2 1877.4 L 231.8 1918.0 L 213.9 1967.2 L 215.9 2025.5 L 243.3 2087.5 L 283.3 2142.3 L 330.2 2191.3 L 381.8 2236.1 L 436.0 2277.7 L 490.6 2317.1 L 543.5 2355.3 L 592.5 2393.0 L 635.5 2431.0 L 670.3 2470.0 L 695.3 2510.4 L 708.9 2553.2 L 709.8 2600.2 L 696.2 2652.2 L 670.6 2699.1 L 635.5 2738.9 L 593.0 2773.1 L 545.0 2802.7 L 493.9 2829.1 L 441.9 2853.6 L 391.6 2877.6 L 345.0 2902.7 L 304.5 2930.8 L 272.7 2964.1 L 253.1 3004.4 L 249.7 3052.2 L 264.7 3107.0 L 301.0 3161.2 L 341.1 3208.0 L 384.2 3249.6 L 428.8 3286.7 L 473.3 3319.8 L 516.3 3349.7 L 556.3 3376.9 L 591.5 3402.0 L 620.5 3425.2 L 641.7 3446.8 L 653.9 3466.5 L 657.4 3484.8 L 650.3 3512.6 L 654.6 3538.2 L 665.1 3559.1 L 672.3 3580.1 L 677.0 3602.9 L 679.3 3627.1 L 679.0 3652.1 L 676.2 3677.7 L 670.8 3703.3 L 662.8 3728.6 L 652.2 3753.1 L 639.1 3776.4 L 623.5 3798.1 L 605.3 3818.0 L 583.2 3836.8 L 556.4 3854.0 L 528.6 3866.3 L 500.2 3874.0 L 471.8 3877.2 L 444.0 3876.2 L 417.3 3871.2 L 392.4 3862.3 L 369.9 3849.8 L 350.3 3834.0 L 334.0 3815.0 L 321.7 3792.9 L 313.9 3767.9 L 311.0 3739.9 L 313.0 3711.6 L 319.0 3685.9 L 328.5 3663.0 L 341.2 3643.0 L 356.6 3625.8 L 374.3 3611.6 L 393.9 3600.5 L 415.0 3592.5 L 437.2 3587.7 L 460.1 3586.4 L 483.2 3588.5 L 506.0 3594.3 L 528.1 3603.7 L 545.9 3614.9 L 559.4 3627.2 L 570.3 3640.9 L 578.5 3655.6 L 584.2 3671.2 L 587.4 3687.2 L 588.3 3703.5 L 587.0 3719.7 L 583.3 3735.6 L 577.3 3750.7 L 569.0 3764.7 L 558.7 3777.3 L 546.3 3788.3 L 531.8 3797.4 L 516.7 3804.3 L 501.5 3809.1 L 486.4 3811.8 L 471.8 3812.6 L 457.8 3811.6 L 444.6 3808.9 L 432.6 3804.5 L 421.8 3798.6 L 412.5 3791.4 L 404.9 3782.8 L 399.3 3773.0 L 395.6 3762.1 L 394.3 3749.9 L 394.9 3737.6 L 397.0 3726.2 L 400.5 3715.9 L 405.1 3706.9 L 410.7 3699.1 L 417.1 3692.7 L 424.3 3687.6 L 432.1 3684.0 L 440.3 3681.9 L 448.9 3681.3 L 457.7 3682.5 L 466.6 3685.3 L 475.5 3690.1 L 482.8 3695.6 L 488.9 3700.0 L 494.3 3703.6 L 499.1 3706.3 L 503.3 3708.3 L 506.8 3709.5 L 509.8 3710.1 L 512.3 3709.9 L 514.3 3708.9 L 515.3 3707.0 L 515.1 3704.8 L 514.0 3702.8 L 512.4 3700.6 L 510.9 3699.2 L 509.1 3700.8 L 510.8 3703.0 L 511.8 3704.7 L 512.2 3705.9 L 512.1 3706.3 L 511.9 3706.3 L 511.2 3706.3 L 509.5 3706.1 L 507.1 3705.2 L 503.8 3703.7 L 499.9 3701.5 L 495.2 3698.5 L 489.9 3694.6 L 483.8 3689.7 L 475.3 3683.6 L 465.6 3678.8 L 455.8 3676.0 L 445.9 3675.2 L 436.2 3676.1 L 426.9 3678.9 L 418.1 3683.4 L 410.1 3689.4 L 402.9 3697.0 L 396.8 3706.1 L 391.8 3716.5 L 388.3 3728.1 L 386.2 3740.9 L 385.8 3754.8 L 388.0 3768.3 L 392.8 3780.6 L 399.9 3791.7 L 409.1 3801.3 L 420.1 3809.3 L 432.6 3815.7 L 446.4 3820.3 L 461.2 3823.0 L 476.9 3823.8 L 493.1 3822.5 L 509.7 3819.1 L 526.5 3813.5 L 543.2 3805.4 L 558.8 3794.9 L 572.3 3782.1 L 583.6 3767.6 L 592.5 3751.5 L 598.9 3734.3 L 602.9 3716.3 L 604.3 3697.8 L 602.8 3679.1 L 598.4 3660.7 L 591.2 3642.8 L 580.9 3625.9 L 567.5 3610.4 L 550.9 3596.5 L 528.6 3583.7 L 503.5 3574.2 L 477.8 3568.8 L 451.9 3567.3 L 426.3 3569.8 L 401.4 3576.1 L 377.8 3586.2 L 356.0 3599.8 L 336.3 3617.0 L 319.4 3637.6 L 305.7 3661.5 L 295.8 3688.5 L 290.2 3718.5 L 289.3 3751.1 L 294.4 3782.5 L 305.1 3810.8 L 321.0 3835.9 L 341.1 3857.2 L 365.0 3874.6 L 391.7 3887.9 L 420.8 3896.9 L 451.5 3901.4 L 483.3 3901.3 L 515.5 3896.3 L 547.5 3886.2 L 578.7 3870.9 L 608.2 3850.1 L 630.6 3829.8 L 650.2 3807.2 L 666.9 3782.6 L 680.8 3756.4 L 691.8 3729.1 L 699.9 3701.2 L 705.3 3672.9 L 707.8 3644.6 L 707.5 3616.8 L 704.3 3589.9 L 698.1 3564.1 L 689.0 3539.9 L 678.7 3522.0 L 684.2 3501.9 L 687.6 3476.0 L 678.4 3446.4 L 659.0 3419.4 L 632.1 3393.9 L 599.2 3368.4 L 561.6 3341.9 L 520.8 3313.7 L 478.0 3283.1 L 434.7 3249.5 L 392.3 3212.3 L 352.3 3171.1 L 316.3 3125.4 L 289.5 3077.0 L 282.9 3036.3 L 289.8 3003.1 L 308.5 2974.6 L 338.2 2948.7 L 377.3 2924.5 L 423.6 2901.2 L 474.4 2877.6 L 527.4 2852.4 L 580.1 2824.0 L 630.1 2790.8 L 674.9 2751.1 L 711.7 2703.0 L 737.6 2645.3 L 748.1 2584.8 L 741.8 2529.3 L 721.0 2478.8 L 688.8 2432.9 L 647.9 2390.6 L 600.5 2350.7 L 548.9 2311.8 L 495.2 2273.1 L 441.3 2233.5 L 389.5 2192.1 L 341.9 2148.3 L 300.4 2101.1 L 267.4 2050.9 L 252.2 2001.1 L 256.0 1961.0 L 273.8 1926.9 L 304.5 1896.5 L 346.8 1868.9 L 398.1 1843.3 L 455.4 1818.6 L 515.9 1793.7 L 576.7 1766.8 L 635.0 1736.5 L 688.2 1700.7 L 733.1 1657.6 L 766.4 1605.3 L 784.1 1543.5 L 783.3 1483.2 L 765.9 1428.0 L 735.3 1377.9 L 694.5 1332.1 L 646.4 1289.4 L 593.3 1248.7 L 537.6 1209.0 L 481.6 1169.6 L 427.8 1129.6 L 378.5 1088.5 L 336.1 1045.7 L 302.7 1000.9 L 280.7 954.5 L 276.9 907.7 L 287.0 868.9 L 309.4 835.3 L 342.8 805.2 L 385.7 778.0 L 435.5 753.1 L 489.5 729.6 L 545.1 706.3 L 599.8 682.0 L 651.0 655.2 L 696.3 624.1 L 732.9 586.7 L 756.8 541.7 L 765.6 491.9 L 763.7 444.7 L 753.4 399.9 L 736.5 357.3 L 714.7 316.7 L 689.7 277.6 L 662.8 239.7 L 635.7 202.7 L 609.7 166.2 L 586.2 130.2 L 566.6 94.6 L 552.1 59.2 L 543.6 23.1 L 541.9 -2.3 Z`

// Section height and derived scroll travel
const SECTION_HEIGHT_VH = 500
const SCROLL_TRAVEL_VH = SECTION_HEIGHT_VH - 100

// SVG viewBox dimensions — adjusted for new path bounds
const VB_W = 1000
const VB_H = 4200

// ---------------------------------------------------------------------------
// Text strings that appear along the trail at various scroll positions.
// ---------------------------------------------------------------------------

interface TrailText {
  text: string
  pathFraction: number
  topPct: number
  side: 'left' | 'right'
  fontSize?: string
  fontWeight?: number
}

function computeTopPct(pathFraction: number): number {
  return ((pathFraction * SCROLL_TRAVEL_VH + 50) / SECTION_HEIGHT_VH) * 100
}

const TRAIL_TEXTS: TrailText[] = [
  {
    text: 'Peter Evan Rodriguez',
    pathFraction: 0.08,
    topPct: computeTopPct(0.08),
    side: 'left',
    fontSize: 'clamp(32px, 3vw, 52px)',
    fontWeight: 600,
  },
  {
    text: 'Nuyorican designer',
    pathFraction: 0.20,
    topPct: computeTopPct(0.20),
    side: 'right',
    fontSize: 'clamp(24px, 2.2vw, 38px)',
    fontWeight: 500,
  },
  {
    text: 'solving hard problems\nwith soft product',
    pathFraction: 0.34,
    topPct: computeTopPct(0.34),
    side: 'left',
    fontSize: 'clamp(26px, 2.4vw, 40px)',
    fontWeight: 500,
  },
  {
    text: 'Squarespace',
    pathFraction: 0.50,
    topPct: computeTopPct(0.50),
    side: 'right',
    fontSize: 'clamp(28px, 2.8vw, 48px)',
    fontWeight: 600,
  },
  {
    text: 'design-minded AI\n& expressibility tools',
    pathFraction: 0.65,
    topPct: computeTopPct(0.65),
    side: 'left',
    fontSize: 'clamp(24px, 2.2vw, 38px)',
    fontWeight: 500,
  },
  {
    text: 'from my dome\nto your chrome',
    pathFraction: 0.80,
    topPct: computeTopPct(0.80),
    side: 'right',
    fontSize: 'clamp(28px, 2.8vw, 46px)',
    fontWeight: 600,
  },
]

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function GraffitiScrollOut() {
  const sectionRef = useRef<HTMLDivElement>(null)
  const centerlineRef = useRef<SVGPathElement>(null)
  const [totalLength, setTotalLength] = useState(0)

  // Measure centerline path length after mount (used for mask dashoffset)
  useEffect(() => {
    const measure = () => {
      if (centerlineRef.current) {
        const len = centerlineRef.current.getTotalLength()
        if (len > 0) setTotalLength(len)
      }
    }
    const raf = requestAnimationFrame(measure)
    return () => cancelAnimationFrame(raf)
  }, [])

  // Scroll-driven animation
  const { scrollYProgress } = useScroll({
    target: sectionRef,
    offset: ['start start', 'end end'],
  })

  // Mask reveal: dashoffset goes from totalLength (hidden) to 0 (fully drawn)
  const dashOffset = useTransform(scrollYProgress, [0, 1], [totalLength, 0])

  // Camera pan: translate the tall inner container upward as user scrolls
  const svgTranslateY = useTransform(
    scrollYProgress,
    [0, 1],
    [0, -SCROLL_TRAVEL_VH],
  )
  const svgY = useTransform(svgTranslateY, (v) => `${v}vh`)

  return (
    <section
      ref={sectionRef}
      data-scroll
      data-scroll-section
      style={{
        height: `${SECTION_HEIGHT_VH}vh`,
        position: 'relative',
      }}
    >
      {/* Sticky viewport — clips the tall inner content */}
      <div
        style={{
          position: 'sticky',
          top: 0,
          height: '100vh',
          width: '100%',
          overflow: 'hidden',
        }}
      >
        {/* Tall inner container — panned vertically by scroll */}
        <motion.div
          style={{
            height: `${SECTION_HEIGHT_VH}vh`,
            width: '100%',
            position: 'relative',
            y: svgY,
          }}
        >
          {/* SVG brush trail — filled shape revealed by centerline mask */}
          <svg
            viewBox={`0 0 ${VB_W} ${VB_H}`}
            preserveAspectRatio="xMidYMin slice"
            style={{
              position: 'absolute',
              inset: 0,
              width: '100%',
              height: '100%',
            }}
          >
            <defs>
              {/* Organic brush-edge roughening filter */}
              <filter
                id="brush-roughen"
                x="-5%"
                y="-5%"
                width="110%"
                height="110%"
              >
                <feTurbulence
                  type="turbulence"
                  baseFrequency="0.015"
                  numOctaves="4"
                  seed={42}
                  result="noise"
                />
                <feDisplacementMap
                  in="SourceGraphic"
                  in2="noise"
                  scale={6}
                  xChannelSelector="R"
                  yChannelSelector="G"
                />
              </filter>

              {/* Mask: centerline path with thick stroke, animated dashoffset */}
              {/* White = visible, black = hidden. The stroke progressively    */}
              {/* reveals the filled brush shape beneath as user scrolls.      */}
              <mask id="brush-reveal-mask">
                <motion.path
                  ref={centerlineRef}
                  d={CENTERLINE_D}
                  fill="none"
                  stroke="white"
                  strokeWidth={60}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeDasharray={totalLength}
                  style={{ strokeDashoffset: dashOffset }}
                />
              </mask>
            </defs>

            {/* Filled brush shape — variable width, revealed by mask */}
            <path
              d={BRUSH_OUTLINE_D}
              fill="#0E0E0E"
              mask="url(#brush-reveal-mask)"
              filter="url(#brush-roughen)"
            />
          </svg>

          {/* Text labels along the trail */}
          {TRAIL_TEXTS.map((item, i) => (
            <TrailTextLabel
              key={i}
              item={item}
              scrollYProgress={scrollYProgress}
            />
          ))}
        </motion.div>
      </div>
    </section>
  )
}

// ---------------------------------------------------------------------------
// Individual text label — fades in when scroll reaches its threshold
// ---------------------------------------------------------------------------

function TrailTextLabel({
  item,
  scrollYProgress,
}: {
  item: TrailText
  scrollYProgress: ReturnType<typeof useScroll>['scrollYProgress']
}) {
  const revealStart = item.pathFraction
  const revealEnd = revealStart + 0.04

  const opacity = useTransform(scrollYProgress, [revealStart, revealEnd], [0, 1])
  const translateY = useTransform(scrollYProgress, [revealStart, revealEnd], [20, 0])

  return (
    <motion.div
      style={{
        position: 'absolute',
        top: `${item.topPct}%`,
        ...(item.side === 'left'
          ? { left: 'clamp(24px, 5vw, 80px)' }
          : { right: 'clamp(24px, 5vw, 80px)' }),
        y: translateY,
        opacity,
        textAlign: item.side === 'left' ? 'left' : ('right' as const),
        whiteSpace: 'pre-line',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: item.fontSize || 'clamp(24px, 2.2vw, 38px)',
        fontWeight: item.fontWeight || 500,
        lineHeight: 1.2,
        letterSpacing: '-0.03em',
        color: '#0E0E0E',
        pointerEvents: 'none',
        maxWidth: 'min(440px, 38vw)',
      }}
    >
      {item.text}
    </motion.div>
  )
}
